In [8]:
import pandas as pd
import random
import numpy as np
from random import randint
df2 = pd.read_csv (r'C:\Users\User\10_titik_lengkap.csv')

In [9]:
df=df2['bobot_'+str(1)]

In [10]:
df2

,bobot_1,bobot_2,bobot_3,bobot_4,bobot_5,bobot_6,bobot_7,bobot_8,bobot_9,bobot_10,...,bobot_21,bobot_22,bobot_23,bobot_24,bobot_25,bobot_26,bobot_27,bobot_28,bobot_29,bobot_30
0,115,140,515,446,467,91,908,119,170,693,...,768,740,101,444,640,771,40,818,766,251
1,74,496,440,180,409,71,698,419,293,482,...,284,572,537,488,378,271,300,67,338,241
2,42,203,27,136,753,337,815,45,909,203,...,380,447,532,280,438,198,692,645,15,593
3,955,352,383,42,49,199,693,594,939,761,...,654,835,385,539,923,961,271,457,223,855
4,712,933,590,640,84,901,576,705,108,935,...,974,427,254,556,222,81,731,915,904,601
5,660,225,231,903,736,326,105,304,618,35,...,276,807,490,829,428,475,598,691,593,302
6,697,559,883,250,326,800,466,560,759,980,...,631,362,403,898,679,296,732,628,211,847
7,450,760,718,506,622,303,310,675,837,951,...,986,832,616,901,972,940,52,673,708,986
8,806,850,41,603,503,872,945,200,63,913,...,480,120,427,430,455,530,207,54,379,863
9,391,790,467,913,472,461,445,150,92,505,...,669,221,42,500,934,262,237,370,115,792
10,504,863,128,500,600,651,268,14,157,495,...,854,109,932,683,60,377,222,883,966,203
11,597,504,62,171,609,304,767,809,887,199,...,398,276,813,62,691,971,169,246,985,535
12,537,19,97,11,245,654,825,595,666,387,...,204,741,278,379,356,243,566,372,790,495
13,452,31,528,606,896,79,833,213,692,857,...,81,978,38,379,41,597,503,698,820,934
14,709,47,760,9,256,287,755,121,967,244,...,832,352,309,806,905,831,573,707,744,223
15,452,494,467,273,719,630,506,58,216,188,...,591,368,810,256,934,578,136,693,244,262
16,784,358,617,330,932,172,399,606,849,748,...,857,403,116,995,239,750,511,629,304,195
17,939,283,266,672,282,666,177,341,262,791,...,524,505,708,776,900,510,218,490,352,222
18,472,139,280,175,493,619,593,216,177,775,...,750,921,192,826,713,584,504,170,5,999
19,372,361,7,471,481,260,412,986,768,704,...,741,757,785,776,160,332,908,474,856,79
20,272,189,291,530,289,472,278,522,249,731,...,682,884,875,761,175,333,794,869,694,607
21,250,554,815,304,519,271,811,172,874,737,...,766,369,317,719,355,823,871,438,242,985
22,644,376,632,627,238,995,950,839,342,297,...,179,886,971,538,927,793,257,806,919,300
23,354,987,937,710,62,660,115,900,879,697,...,565,545,390,929,613,209,633,932,759,919
24,212,813,719,467,295,35,730,846,19,210,...,671,639,19,3,141,522,944,178,225,83
25,515,956,220,866,994,175,936,744,199,332,...,348,253,645,390,395,260,487,114,649,267
26,132,283,525,679,258,272,161,160,900,620,...,324,750,523,489,307,14,88,991,337,161
27,248,588,537,450,447,539,141,633,487,398,...,306,251,178,458,329,377,446,637,844,521
28,603,762,64,950,873,357,729,952,506,625,...,216,187,696,684,274,477,263,603,87,954
29,642,822,894,39,908,857,233,712,236,337,...,102,857,163,804,768,139,156,853,217,734
30,935,646,245,452,233,592,690,339,771,926,...,735,807,87,81,237,858,593,783,386,78
31,70,253,930,747,691,447,636,422,675,669,...,983,926,796,127,266,248,303,772,853,205
32,715,317,333,218,317,927,282,130,880,818,...,386,781,699,291,145,410,808,271,906,326
33,328,200,271,939,337,928,856,735,679,129,...,114,605,618,360,674,407,636,427,400,23
34,24,605,664,788,739,997,680,16,965,429,...,637,112,532,18,188,208,925,229,427,59
35,426,601,274,209,752,827,857,186,988,104,...,711,559,304,198,718,490,890,185,162,927
36,987,777,853,842,72,605,960,38,648,515,...,389,411,459,540,453,881,233,118,344,676
37,72,515,547,390,64,796,498,927,723,409,...,619,473,935,915,867,855,8,208,990,258
38,227,361,991,66,725,481,518,860,824,406,...,696,743,271,99,689,782,942,858,869,264
39,144,626,894,796,575,477,256,238,710,428,...,221,882,237,969,260,762,791,171,722,538
40,814,656,13,302,888,609,942,76,166,265,...,287,693,976,414,152,469,596,577,104,49
41,82,575,470,566,677,132,785,225,332,253,...,901,851,555,133,749,158,163,92,834,819
42,740,129,307,967,183,780,374,46,596,978,...,618,509,49,30,302,733,312,768,58,424
43,703,26,461,664,132,262,118,23,831,651,...,843,434,605,145,859,63,162,300,245,896
44,886,958,998,171,572,562,969,437,375,109,...,333,828,592,511,141,107,17,790,6,104

In [11]:
global titik
titik = []
for i in range(1,11):
    titik.append(i)

In [12]:
titik

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
membuat_tabel(titik)

In [13]:
def membuat_tabel(n): #membuat himpunan1
    global sumber1,df
    sumber1 =[]

    i = 0
    while i < len(n):    
        for j in range(len(n)-1,0,-1):

            k=0
            while k < j:
                sumber1.append(n[i])

                k+=1
            i+=1   
            if len(sumber1)==int(len(n)*(len(n)-1)/2):
                break
        if len(sumber1)==int(len(n)*(len(n)-1)/2):
            break

    global tujuan1
    tujuan1 = []
    for i in range(1,len(n)):
        a = n[i:len(n)]
        for j in range(len(a)):
            tujuan1.append(a[j])
    
    
    data= {"sumber":sumber1,
            "tujuan":tujuan1,
              "bobot":df}
    df = pd.DataFrame(data)

In [35]:
df

     sumber  tujuan  bobot
0         1       2    852
1         1       3    400
2         1       4    844
3         1       5    872
4         1       6    574
..      ...     ...    ...
185      17      19    475
186      17      20    866
187      18      19    462
188      18      20    326
189      19      20    459

[190 rows x 3 columns]

In [15]:
def awal(df): #mendeklarasikan semua vortex dalam graf
    global vortex,graf,root
    vortex = []
    
    for i in range(len(df)):
        if df.iloc[i]['tujuan'] not in vortex:
            vortex.append(df.iloc[i]['tujuan'])
        if df.iloc[i]['sumber'] not in vortex:
            vortex.append(df.iloc[i]['sumber'])
    vortex
    #membuar akar random dari Graph
    
    root= 1 #mencari titik awal dengan random 
    graf=pd.DataFrame( columns = ['sumber', 'tujuan', 'bobot'])
    for i in range(len(df)):
        if df.iloc[i]['tujuan'] == root:
            graf = graf.append(df.iloc[i])
        if df.iloc[i]['sumber'] == root:
            graf = graf.append(df.iloc[i])
    graf=graf.sort_values(by=['bobot']) #mengambil sisi paling minimum pada root 
    graf = graf.iloc[[0]]

In [19]:
awal(df)

In [20]:
graf

  sumber tujuan bobot
2      1      4    42

In [21]:
def eleminasi():
    global vortex1
    vortex1 = []
    for i in range(len(graf)): #mengambil titik yang sudah di pilih di vortex
        if graf.iloc[i]['tujuan'] not in vortex1:
            vortex1.append(graf.iloc[i]['tujuan'])
        if graf.iloc[i]['sumber'] not in vortex1:
            vortex1.append(graf.iloc[i]['sumber'])
    
    global sementara,tes  #mengambil sisi yang terhubung pada V
    sementara = pd.DataFrame( columns = ['sumber', 'tujuan', 'bobot'])
    for i in range(len(df)):
        if df.iloc[i]['sumber'] in vortex1:
            if df.iloc[i]['tujuan'] not in vortex1:
                sementara=sementara.append(df.iloc[[i]])
        if df.iloc[i]['tujuan'] in vortex1:
            if df.iloc[i]['sumber'] not in vortex1:
                sementara=sementara.append(df.iloc[[i]])
    
    
    
    tes = pd.DataFrame( columns = ['sumber', 'tujuan', 'bobot'])
    for i in range(len(sementara)): #mengeleminasi sisi yang menyebabkan looping
        if sementara.iloc[i]['tujuan'] not in vortex1:
            if sementara.iloc[i]['sumber'] in vortex1:
                tes = tes.append(sementara.iloc[[i]])
        if sementara.iloc[i]['sumber'] not in vortex1:
            if sementara.iloc[i]['tujuan'] in vortex1:
                tes = tes.append(sementara.iloc[[i]])

In [22]:
def sort():
    global minimum,tes
    tes = tes.sort_values(by=['bobot'])
    minimum = tes.iloc[[0]]

In [25]:
def mst(df):
    global graf,bobot_total
    
    awal(df)
    while (len(graf))<(len(vortex)-1):
        try:
            eleminasi()
            sort()
            graf=graf.append(minimum)
            
            if len(graf)==len(vortex):
                break
        except IndexError:
            break
    bobot_total = 0
    for i in range(len(graf)):
        bobot = int(graf.iloc[i]['bobot'])
        bobot_total += bobot
    print(bobot_total)

In [24]:
global hasil_mst
hasil_mst = []
for i in range(1,31):

    df=df2['bobot_'+str(i)]
    membuat_tabel(titik
    mst(df)

bobot totalnya ialah  900
bobot totalnya ialah  923
bobot totalnya ialah  746
bobot totalnya ialah  858
bobot totalnya ialah  1248
bobot totalnya ialah  1347
bobot totalnya ialah  1912
bobot totalnya ialah  466
bobot totalnya ialah  1478
bobot totalnya ialah  1519
bobot totalnya ialah  1184
bobot totalnya ialah  1703
bobot totalnya ialah  838
bobot totalnya ialah  1126
bobot totalnya ialah  747
bobot totalnya ialah  726
bobot totalnya ialah  777
bobot totalnya ialah  1011
bobot totalnya ialah  822
bobot totalnya ialah  1306
bobot totalnya ialah  1677
bobot totalnya ialah  2088
bobot totalnya ialah  793
bobot totalnya ialah  1234
bobot totalnya ialah  1237
bobot totalnya ialah  1262
bobot totalnya ialah  910
bobot totalnya ialah  1240
bobot totalnya ialah  775
bobot totalnya ialah  1030

In [29]:
global hasil_mst
hasil_mst = []
for i in range(1,31):

    df=df2['bobot_'+str(i)]
    membuat_tabel(titik)
    mst(df)

900
923
746
858
1248
1347
1912

KeyboardInterrupt:

In [30]:
graf

   sumber tujuan bobot
2       1      4    45
10      2      4    14
15      2      9    58

In [38]:
global hasil_mst
hasil_mst = []
for i in range(1,31):

    df=df2['bobot_'+str(i)]
    membuat_tabel(titik)
    mst(df)

bobot totalnya ialah  982
bobot totalnya ialah  1192
bobot totalnya ialah  851
bobot totalnya ialah  1244
bobot totalnya ialah  1331
bobot totalnya ialah  1012
bobot totalnya ialah  1389
bobot totalnya ialah  1552
bobot totalnya ialah  1044
bobot totalnya ialah  903
bobot totalnya ialah  1682
bobot totalnya ialah  1020
bobot totalnya ialah  923
bobot totalnya ialah  1440
bobot totalnya ialah  1162
bobot totalnya ialah  1230
bobot totalnya ialah  1544
bobot totalnya ialah  1634
bobot totalnya ialah  987
bobot totalnya ialah  949
bobot totalnya ialah  1298
bobot totalnya ialah  1088
bobot totalnya ialah  1087
bobot totalnya ialah  1421
bobot totalnya ialah  1259
bobot totalnya ialah  1226
bobot totalnya ialah  1124
bobot totalnya ialah  1265
bobot totalnya ialah  811
bobot totalnya ialah  1233

In [34]:
i

10

In [36]:
vortex = []
for i in range(len(df)):
    if df.iloc[i]['tujuan'] not in vortex:
        vortex.append(df.iloc[i]['tujuan'])
    if df.iloc[i]['sumber'] not in vortex:
        vortex.append(df.iloc[i]['sumber'])

In [37]:
vortex

[2, 1, 3, 4, 5, 6, 7, 8, 9, 10]

In [69]:
minimum

   sumber tujuan bobot
38      6     10   227

In [75]:
global graf

In [77]:
graf.append(minimum)

   sumber tujuan bobot
37      6      9    72
38      6     10   227

In [78]:
graf

   sumber tujuan bobot
37      6      9    72

In [80]:
awal(df)

In [81]:
graf

   sumber tujuan bobot
34      5     10    24

In [87]:
df=df1['bobot_'+str(2)]
membuat_tabel(titik)
mst(df)

bobot totalnya ialah  923

In [86]:
graf

   sumber tujuan bobot
9       2      3   150
10      2      4    14
2       1      4    45
15      2      9    58
42      8      9    46
43      8     10    23
34      5     10    16
36      6      8    38
40      7      9    76